name: 'Terraform EC2 Workflow'

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch: # Manual trigger
    inputs:
      destroy:
        description: 'Trigger Terraform Destroy (Rollback)'
        required: false
        default: 'false'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.9.8  # Specify your Terraform version here

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply --auto-approve

    - name: Terraform Destroy (Rollback)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
      run: terraform destroy --auto-approve

